name: 14- Caching

on:
    workflow_dispatch:
        inputs:
            use-cache:
              description: Whether to use cache step
              type: boolean
              default: true
              
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
             working-directory: 14-Caching/my-react-app
        steps:
            - name: Checkout code
              uses: action/checkout@v4
            - name: Setup Node
              uses: action/setup-node@v3
              with:
                node-version: '20.x'
            - name: Install dependencies
              run: npm ci
            - name: Testing
              run: npm run test
            - name: Building
              run: npm run build
            - name: Deploying to nonprod
              run: echo" Deploying to nonprod"
              