name: 18.3 - Reusable Workflows

on: 
    workflow_dispatch:

jobs:
    deploy:
        uses: ./.github/workflows/18-1-reusable-workflows.yaml
        with:
            target-directory: dummy-dir
    e2e-tests:
        uses: shanna33/Github-action-courses/.github/workflows/e2e.yaml@main


   